### PR TITLE
Centered div

### PR DESCRIPTION
**Pull request by aditya28sarin**

### CODE REVIEW

**Comment by rdvhoorn** [comment]
Love the enthusiasm. Few things, im not sure why you changed the Angular.json? Could be an accident? Second, the DHC thingy was not the only label, so just add the css class to the other squares as well and it should be gucci!

Did you follow the readme for trying to run it locally?

**Comment by aditya28sarin** [comment]
Okay, I'll do that! Ya my bad, I forgot to add the classes to other divs

**Comment by rdvhoorn** [comment]
No problem! The documentation is not all to up to date sadly. Not sure if you are in the webcommittee drive as well? There is a document on how to setup the backend as well. Just checked out your branch, but the centering is currently also not working. If you don't manage to run the frontend locally after setting up the backend (make sure to put the backend clone next to the frontend clone), then lemme know

**Comment by aditya28sarin** [comment]
I cloned the "backend" repo and placed it just next to the frontend folder and then tried to run `ng serve` inside the the frontend repo, but still it is running at `localhost:80` but with a blank screen

**Comment by rdvhoorn** [comment]
Dont try anymore

I love that you actually tried to contribute lol, but failed to center a div correctly.
Nevertheless, you are not from our organization, and you tried to get info by adding the analytics stuff to our Angular.json. Got admit that I did not expect it, but I also love that you failed to do a 'good first issue' while claiming to be an experienced web developer

**Pull request closed without merging**
